### ISSUE TITLE
how to correctly detect the draw in classic chess?

### ISSUE THREAD

**Issue by sowson** [kz04px/libchess#10]
I am loading position (2 kings only on the board) and Draw is not detected. What may do to detect it? Checkmate, in addition, works perfectly :).

**Comment by sowson** [comment]
By the way, stalemate also not working, IMHO... not sure why? ;-(.

**Comment by kz04px** [comment]
> I am loading position (2 kings only on the board) and Draw is not detected.

Insufficient material is not considered.

> stalemate also not working

I'd need an example position to comment on this.

**Comment by sowson** [comment]
It looks like the draw is not working, or I have some other error. Can you check? Thanks!
fen: 8/8/8/8/8/2k5/8/6K1 w - - 1766 1176
pgn: g1f1
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ♔  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ·  ·
 ·  ·  ·  ·  ·  ·  ♚  ·
Castling:
EP: -
Turn: w

**Comment by kz04px** [comment]
The position you've shown is indeed a draw by insufficient material. However, as we can see from the code sample below, it is not factored in to the `is_draw()` detection:
```C++
[[nodiscard]] bool is_draw() const noexcept {
    return (threefold() || fiftymoves()) && !is_checkmate();
}
```
I suppose you could say that this function is technically misleading or incomplete. However, writing one that truly detects whether the game is over is a practical impossibility. As such, it only considers the main rules that concretely state the game is over.

Here's another example of a drawn position that is not detected:
`4k3/8/8/p1p1p1p1/P1P1P1P1/8/8/4K3 w - - 0 1` [lichess](https://lichess.org/analysis/4k3/8/8/p1p1p1p1/P1P1P1P1/8/8/4K3_w_-_-_0_1)

**Comment by sowson** [comment]
ok, and how to use threefold() I need to stay in the buffer last 6 positions? FEN is stateless, right?

**Comment by sowson** [comment]
btw, I make a counter of pieces to solve the draw issue, if there are only 2 Kings, is draw for sure ;-). same if only king and knight or bishop, so I somehow covered this. thanks again for the great work on this repo!

**Comment by kz04px** [comment]
> ok, and how to use threefold() I need to stay in the buffer last 6 positions? FEN is stateless, right?

Just call the function as you would any other. The buffer you're speaking of is stored inside the Position class and is updated by the `makemove` function whenever a move is applied. Indeed, it would only ever return `true` if at least six moves have been made.

**Comment by sowson** [comment]
Thanks! :-). All done. Thanks for your input!
