### ISSUE TITLE
No makefile

### ISSUE THREAD

**Issue by jevetts1** [kz04px/libchess#11]
Hi I have been trying to build and use this library for a few hours but when it comes to the last step to run "make" in the command line, it always fails, as there is no makefile in the build folder. Any ideas why this might be?

**Comment by kz04px** [comment]
Chances are the build instructions provided aren't very good. Please try the following instead:
```
cmake ..
cmake --build .
```

**Comment by jevetts1** [comment]
Thank you for your response - I tried that and am getting this error:

$ cmake --build .
MSBuild version 17.4.1+9a89d02ff for .NET Framework
cl : command line  error D8021: invalid numeric argument '/Wextra'
[C:\Users\jayde\Documents\Programming\python chess
bot\chessBotCPP\libchess\build\libchess-shared.vcxproj]
cl : command line  error D8021: invalid numeric argument '/Wextra'
[C:\Users\jayde\Documents\Programming\python chess
bot\chessBotCPP\libchess\build\libchess-static.vcxproj]

**Comment by kz04px** [comment]
Sounds like I'm using some flags that your compiler doesn't enjoy. Go to `CMakeLists.txt` in the root directory and remove `-Wextra` from line 12 and anything else it complains about.

**Comment by jevetts1** [comment]
Cool, that seems to have worked -thank you. I am a massive noob to C++ libraries, do you know which file I need to include in my main cpp file in order to have access to the library? Thank you Sent from Mail for Windows From: kz04pxSent: 08 January 2023 23:08To: kz04px/libchessCc: jevetts1; AuthorSubject: Re: [kz04px/libchess] No makefile (Issue #11) Sounds like I'm using some flags that your compiler doesn't enjoy. Go to CMakeLists.txt in the root directory and remove -Wextra from line 12 and anything else it complains about.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
