### ISSUE TITLE
Wrong moves in Chess960 as Legal from FEN

### ISSUE THREAD

**Issue by sowson** [kz04px/libchess#12]
Wrong Move: f1g1 on: brnbqkrn/pppppppp/8/8/8/8/PPPPPPPP/BRNBQKRN w KQkq - 0 1

![Screen Shot 2023-03-11 at 05 04 09](https://user-images.githubusercontent.com/33941184/224463919-b5de43a1-6a8a-4c19-a733-14be101ef186.png)

**Comment by sowson** [comment]
Wrong Move: d1b1 on: qrnkbbr1/pppppppp/6n1/8/8/1N6/PPPPPPPP/QR1KBBRN w KQkq - 2 2

![Screen Shot 2023-03-11 at 06 29 29](https://user-images.githubusercontent.com/33941184/224466851-d8aa2f5c-3149-4baf-904e-535890de9eea.png)

**Comment by sowson** [comment]
Wrong Move: f1g1 on: r1bb1krq/pppp1ppp/2nn4/4p3/4P3/3N2P1/PPPP1P1P/RNBB1KRQ w KQkq - 2 4

![Screen Shot 2023-03-11 at 06 40 58](https://user-images.githubusercontent.com/33941184/224467232-e3e87765-3000-49b3-8ecf-5b4879a790da.png)

**Comment by sowson** [comment]
(index):398 Wrong Move: f1g1 on: nbrnbkrq/pppppp1p/6p1/8/5P2/8/PPPPP1PP/NBRNBKRQ w KQkq - 0 2

![Screen Shot 2023-03-11 at 06 47 20](https://user-images.githubusercontent.com/33941184/224467427-b2d4199f-735f-4db0-9b90-ab5d84a1f324.png)

**Comment by sowson** [comment]
(index):398 Wrong Move: d8c8 on: bbrkq1n1/p1ppppBN/7p/1p6/1P6/8/P1PPPPPP/1BRKQN1R b Kq - 0 6

![Screen Shot 2023-03-11 at 07 39 49](https://user-images.githubusercontent.com/33941184/224469452-a98cb201-0af4-4651-ac5f-bcd286b3daf6.png)

**Comment by sowson** [comment]
(index):398 Wrong Move: f1b1 on: 7k/8/8/3P2Q1/6N1/8/PP1P2PP/BR3KR1 w Q - 3 24

![Screen Shot 2023-03-11 at 07 50 14](https://user-images.githubusercontent.com/33941184/224469852-44a27f99-6e1c-4280-8b90-5a7e1958c0de.png)

**Comment by sowson** [comment]
Wrong Move: e1h8 on: 1b1r2r1/p1pppkp1/5p1p/3n4/1P3P2/2p5/P7/B1N1K2N w KQ - 0 17

![Screenshot from 2023-03-11 09-29-41](https://user-images.githubusercontent.com/33941184/224474012-e0f62f0c-510a-463d-b46d-d35fec5b8745.png)

**Comment by kz04px** [comment]
The last position is an illegal FEN as it states white can castle both king and queen side despite not having any rooks. The rest of these positions and moves seem to be perfectly legal under 960.

**Comment by kz04px** [comment]
I've added two commits that might help you with your 960 woes:
- 7fb87329dcd32ca0f524902c2731100c90189508 introduces a boolean parameter to toggle DFRC parsing of FEN strings
- 8e1efa14145ae057ff08b6f4d7f37ebd5d808b19 introduces Position::move_string() with a boolean for DFRC

I have also made an attempt to handle illegal castling permissions in FEN strings. The last position you presented now correctly shows as having 15 legal moves instead of 16.

**Comment by kz04px** [comment]
I'll add that when playing 960, you really shouldn't use the standard notation for castling permissions. `KQkq` can be ambiguous under certain circumstances. Instead, the files containing the rooks in question should be specified.

For example:
`rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1` - startpos
`rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w HAha - 0 1` - startpos under 960

`7k/8/8/3P2Q1/6N1/8/PP1P2PP/BR3KR1 w Q - 3 24` - One of your positions above
`7k/8/8/3P2Q1/6N1/8/PP1P2PP/BR3KR1 w B - 3 24` - What it should be

**Comment by sowson** [comment]
Thanks a lot! :-).
