### ISSUE TITLE
Can I obtain from Position the Pieces on the Board collection?

### ISSUE THREAD

**Issue by sowson** [kz04px/libchess#13]
Thank you for your great project! Thanks for it. I build https://iChess.io at last, some techniques work, and you may enjoy it.

Now, I am looking for a collection of pieces on the board. I saw a print method that uses Square and Bitboard. The issue is that I need only existing chess pieces on the board, not a whole board with empty boxes.

The best would be, for example, such usage.

libchess::Position position = libchess::Position(fen);

vector<libchess::BoardPiece> pieces = position.boardpieces();

for(piece : pieces) {
    int row = piece.row;
    int col = piece.col;
    char color = piece.color; // or libchess::Side
    char piece = piece.piece; // or libchess::Piece
    // super cool code I can share on private :D
}

Can you help me make that? I was trying with external code. The issue was that I love:

position.makemove(move) and position.undomove() functions ;-). And that is hard to track.

I appreciate any help you can provide.

**Comment by kz04px** [comment]
I've updated master to allow the following code. Is this okay?
```C++
#include <iostream>
#include <libchess/position.hpp>

int main() {
    const auto pos = libchess::Position("startpos", true);

    std::cout << pos << std::endl;

    for (const auto side : libchess::sides) {
        for (const auto piece : libchess::pieces) {
            for (const auto sq : pos.pieces(side, piece)) {
                std::cout << "sq(" << sq << ")";
                std::cout << " piece(" << piece << ")";
                std::cout << " colour(" << side << ")";
                std::cout << std::endl;
            }
        }
    }

    return 0;
}
```

**Comment by sowson** [comment]
You made my day!!! ;-). Thanks a lot! It was super fast now it is ultra super fast solution! :D.

**Comment by kz04px** [comment]
You're welcome.
