### ISSUE TITLE
How to test agains wrong moves?

### ISSUE THREAD

**Issue by sowson** [kz04px/libchess#14]
Wrong Move: e5f3 on: r1bqkb1r/pppppppp/7n/4n3/2B5/4PQ2/PPPP1PPP/RNBK2NR b kq - 6 4

![Screenshot from 2023-09-07 20-30-16](https://github.com/kz04px/libchess/assets/33941184/4e82f280-619f-46cc-8a8b-f49eaf32fc3c)

Can you tell me how to test such case? I am using a bit older version of your code, thank you very much!

**Comment by sowson** [comment]
PGN: 1. e3 Nc6 2. Qf3 Nh6 3. Bc4 Ne5 4. Bxf7+

**Comment by sowson** [comment]
I have just tested on latest code from master branch. Please help ;-).

**Comment by kz04px** [comment]
That FEN string doesn't match the position or move sequence provided, the correct one is `r1bqkb1r/pppppBpp/7n/4n3/8/4PQ2/PPPP1PPP/RNB1K1NR b KQkq - 0 4`

Using the split perft provided, you can see that it gives the correct output:
```
./split 1 r1bqkb1r/pppppBpp/7n/4n3/8/4PQ2/PPPP1PPP/RNB1K1NR b KQkq - 0 4
r-bqkb-r
pppppBpp
-------n
----n---
--------
----PQ--
PPPP-PPP
RNB-K-NR
Castling: KQkq
EP: -
Turn: b

1 e5f7: 1
2 h6f7: 1

Time 0ms
Nodes 2
```

Let me know if this was in fact the issue. If not, please clarify and I'll look into it. Thanks.

**Comment by sowson** [comment]
Thank you, let me double check my FEN generation. I will update the issue then. Thanks ;-) :beer:

**Comment by sowson** [comment]
Thank you so much for your help. The bug was on my code. All because I had to fix the situation described below and try to make a castleing move.

fen: r1bqk2r/pppp1ppp/2n1pn2/8/1b6/1PN1PQ2/PBPP1PPP/R3KBNR b KQkq - 2 5
move: c6e5
![Screen Shot 2023-09-07 at 10 10 18 PM](https://github.com/kz04px/libchess/assets/33941184/5a316ae8-1629-4e20-a639-1eb7addabfbe)

PGN: 1. b3 Nf6 2. Bb2 e6 3. Nc3 Nc6 4. e3 Bb4 5. Qf3 Ne5

You may try this at my game online at https://iChess.io site. I am doing it for the publication and later for my Ph.D. How should I put you in Credits (I will add soon on that site) and the publication bibliography?

It is impressive work! Thanks!

**Comment by kz04px** [comment]
No need for acknowledgement as long as the license is followed. If you really want to however, a link to the repo would be more than sufficient.

Good luck with it all.
